services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.

  Commission\Calculation\:
    resource: '../src/*'

  Commission\Calculation\Application:
    public: true

