services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.

  Commission\Calculator\:
    resource: 'src/*'

  Commission\Calculator\Application:
    public: true
